export {default as Introduction} from './Introduction'
export {default as Problem} from './Problem'
export {default as Approach} from './Approach'
export {default as Solution} from './Solution'
export {default as OutComeAndBenefits} from './OutCome'